### ISSUE TITLE
Is This Necessary Anymore And/Or May Conflict with the 'fixed' v0.3.x Rack-Timeout gem?  

### ISSUE THREAD

**Issue by ZiaMM** [keyme/rack-timeout-puma#2]
My H12 Issue Returned, in less virulent form, after a Rack-Timeout upgrade from v0.4.x to v0.3.2.  My thought was that perhaps this gem and the new version of Rack-Timeout could conflict?

**Comment by zsalzbank** [comment]
This gem shouldn't really be needed anymore because of the upgrades to Rack Timeout.
